### ISSUE TITLE
Empty tips on duplicate elements

### ISSUE THREAD

**Issue by yekver** [vadikom/poshytip#12]
I have this code to recieve info via ajax and display it inside poshytip:

``` javascript
    var userDetailsCache = {};
    $("span[class*='img_user-']").poshytip({
        bgImageFrameSize: 11,
        offsetY: 10,
        content: function(updateCallback) {
            var userId = $(this).data('user_id');
            if (userDetailsCache[userId] && userDetailsCache[userId].container) {
                return userDetailsCache[userId].container;
            } else {
                userDetailsCache[userId] = { container: null };
                $.ajax({
                    type: 'post',
                    url: '/get_usr_details',
                    dataType: 'json',
                    data: {
                        userID: userId
                    },
                    success: function (result){
                        var container = $('<div/>');
                        container.append(
                            '<div><strong>Login:</strong> '+result.desc.login+'</div>' +
                            '<div><strong>E-mail:</strong> '+result.desc.email+'</div>' +
                            '<div><strong>Skype:</strong> '+result.desc.skype+'</div>'
                        );
                        // store the content in the cache
                        // and call updateCallback() to update the content in the main tooltip
                        updateCallback(userDetailsCache[userId].container = container);
                    }
                });

                return 'Loading...';
            }
        }
    });
```

Here is the bug:
If I have more then one identical html triggered element tip content is empty.

Ex:

``` html
<span data-user_id="223" class="icn_left bold img_user-6">Dan Brown</span>
<span data-user_id="223" class="icn_left bold img_user-6">Julia Brown</span>
<span data-user_id="223" class="icn_left bold img_user-6">Robert Brown</span>
```

If we drag mouse to each of this html elements and then brag it back to the first of secont element, tip content will be empty (`this.$inner` is empty)

I solve this problem by commenting lines 151,154:

``` javascript
//if (this.content !== newContent) {
      this.$inner.empty().append(newContent);
      this.content = newContent;
//}
```

**Comment by vadikom** [comment]
Yes, those lines seem to cause the issue in your case. However, these are there for another reason - to prevent unneeded emptying of the tip content since it also removes any event handlers, etc. of the content when it's a DOM node(s) - e.g. you will notice that without those lines the yellow tips for the images in the Flickr example won't work after the first time. But in your case the same content (and it's a DOM node) is reused for more than one tip and that check does cause the issue (i.e. the node is always appended to the last shown tip). So to fix the issue for now without needing to modify the script, you could use something like this:

<pre>success: function (result){
    var container = '&lt;div&gt;' +
        '&lt;div&gt;&lt;strong&gt;Login:&lt;/strong&gt; '+result.desc.login+'&lt;/div&gt;' +
        '&lt;div&gt;&lt;strong&gt;E-mail:&lt;/strong&gt; '+result.desc.email+'&lt;/div&gt;' +
        '&lt;div&gt;&lt;strong&gt;Skype:&lt;/strong&gt; '+result.desc.skype+'&lt;/div&gt;' +
    '&lt;/div&gt;';
    // store the content in the cache
    // and call updateCallback() to update the content in the main tooltip
    updateCallback(userDetailsCache[userId].container = container);
}</pre>

When the content is a string, you won't have any issues.

I will also consider a fix for the script when I have a bit more time.. Thanks!
